### ISSUE TITLE
issue in css 

### ISSUE THREAD

**Issue by Surinder05** [mikeott/google-reviews#1]
i think need to attached the css along with this repo.

**Comment by mikeott** [comment]
@Surinder05 Sure why not. Done. I've added some basic CSS. I hope you're cool with SCSS (who writes vanilla CSS anymore?) :-P

**Comment by Surinder05** [comment]
Thank you mike Ott . Yes I can manage .. 

Thank for your help .

**Comment by Surinder05** [comment]
I really appreciate your help, keep posting stuff like that .. 

Keep up the good work

**Comment by mikeott** [comment]
CSS file has been added to the repo.
